import {Su7Prototype,appScreens} from './Su7Prototype';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,ArrowUp,Maximize2,X,Plus,Minus,ArrowRight} from 'lucide-react';
import {categories,projects,sources,pageTitles,pageImage,type Project} from './project-data';
import dimensions from './page-dimensions.json';
import './projects.css';
import {ResearchPanel} from './ResearchPanel';
import {ExperiencePanel,ReflectionPanel} from './ExperiencePanel';
const displayPage=pageImage;
function Cover({project:p}:{project:Project}){return <><img src={p.cover} alt={p.title+' · 项目视觉'} loading="lazy" width="1500" height="900"/><div className="cover-art"><span>{p.category==='interior'?'SPACE / HUMAN / EVERYDAY':p.category==='service'?'PEOPLE / SYSTEM / CONNECTION':'PERCEPTION / PLAY / REFLECTION'}</span><strong>{p.en}</strong><div><span>{p.subtitle}</span><span>Q. / SELECTED WORK</span></div></div><span className="cover-orbit" aria-hidden="true"/></>;}


const totalPages=(p:Project)=>p.chapters.reduce((n,c)=>n+c.pages.length,0);
export function ProjectArchive(){return <section className="archive section wrap" id="work">
 <div className="section-top"><span className="eyebrow">01 / PROJECT ARCHIVE</span><span className="muted">10 个项目 · 3 个设计方向</span></div>
 <div className="archive-intro"><h2>沿着不同的路径，<br/><span className="dim">理解人与世界。</span></h2><p>室内与空间 / 服务 / 概念交互<br/>钱光耀 · 项目作品档案</p></div>
 <nav className="category-jumps" aria-label="作品分类">{categories.map((cat,i)=><a href={'#work-'+cat.id} key={cat.id}><span>0{i+1}</span>{cat.title}<ArrowUpRight size={17}/></a>)}</nav>
 {categories.map((cat,i)=><section className="category-group" id={'work-'+cat.id} key={cat.id} aria-labelledby={'title-'+cat.id}>
  <div className="category-heading"><span className="category-index">0{i+1}</span><div><span className="eyebrow">{cat.en}</span><h3 id={'title-'+cat.id}>{cat.title}</h3></div><p>{cat.intro}</p><span className="category-count">({projects.filter(p=>p.category===cat.id&&!p.supplement).length.toString().padStart(2,'0')})</span></div>
  <div className="archive-grid">{projects.filter(p=>p.category===cat.id&&!p.supplement).map((p,j)=><a className={'archive-card archive-card-'+j} href={'#/project/'+p.id} key={p.id} aria-label={'查看项目：'+p.title}><div className={'archive-cover cover-'+p.id}><Cover project={p}/><span className="archive-open"><ArrowUpRight size={24}/></span><span className="cover-number">{String(j+1).padStart(2,'0')}</span></div><div className="archive-card-meta"><span>{p.tags.join(' / ')}</span><span>{p.chapters.length} 章节</span></div><h4>{p.title}</h4><p>{p.subtitle}</p></a>)}</div>
 </section>)}

 </section>}

export function CaseStudy({project:p,chapterId}:{project:Project;chapterId?:string}){
 const [active,setActive]=useState(p.chapters[0].id);const [lightbox,setLightbox]=useState<number|string|null>(null);const [zoom,setZoom]=useState(1);const modal=useRef<HTMLDialogElement>(null);const heading=useRef<HTMLHeadingElement>(null);
 const category=categories.find(c=>c.id===p.category)!;
 const next=projects[(projects.findIndex(q=>q.id===p.id)+1)%projects.length];
 useEffect(()=>{document.title=p.title+' — Qian Guangyao Portfolio'; if(!chapterId){window.scrollTo({top:0,behavior:'instant'});heading.current?.focus({preventScroll:true});}return()=>{document.title='Qian Guangyao — Portfolio';};},[p.id]);
 useEffect(()=>{if(chapterId)document.getElementById('chapter-'+chapterId)?.scrollIntoView({behavior:'instant',block:'start'});else window.scrollTo({top:0,behavior:'instant'});},[chapterId,p.id]);
 useEffect(()=>{const update=()=>{const line=window.innerHeight*.3;let current=p.chapters[0].id;for(const chapter of p.chapters){const el=document.getElementById('chapter-'+chapter.id);if(el&&el.getBoundingClientRect().top<=line)current=chapter.id;}setActive(current);};window.addEventListener('scroll',update,{passive:true});update();return()=>window.removeEventListener('scroll',update);},[p.id]);
 useEffect(()=>{if(lightbox!==null){setZoom(1);modal.current?.showModal();document.body.style.overflow='hidden';}else{modal.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[lightbox]);
 return <main className="case-study">
 <header className="case-header"><div className="wrap"><a className="case-back" href={'#work-'+p.category}><ArrowLeft size={17}/> 返回{category.title}</a><a href="#home" className="case-brand">GUANGYAO QIAN <span>/ DESIGN</span></a><a href={'#/project/'+p.id+'/'+p.chapters[0].id} className="case-header-count">{totalPages(p)} 页原稿</a></div></header>
 <div className="case-hero wrap"><div className="case-kicker"><span>{category.en}</span><span>{p.supplement?'补充作品':'PROJECT / '+String(projects.findIndex(q=>q.id===p.id)+1).padStart(2,'0')}</span></div><h1 ref={heading} tabIndex={-1}>{p.title}</h1><div className="case-subhead"><p className="case-description">{p.description}</p><span>{p.en}</span></div><div className={'case-hero-image cover-'+p.id}><Cover project={p}/></div>
 <div className="case-facts"><div><span>项目方向</span><p>{p.tags.join(' · ')}</p></div><div><span>项目背景</span><p>{p.context}</p></div><div><span>阅读内容</span><p>{p.chapters.length} 个章节 / {totalPages(p)} 页原稿</p></div></div>{p.credits&&<p className="case-credits">团队署名　{p.credits}</p>}{p.note&&<p className="case-note">{p.note}</p>}</div>
 <div className="case-layout wrap"><aside className="case-toc" aria-label="项目章节目录"><p>项目目录 <span>CONTENTS</span></p><nav>{p.chapters.map((c,i)=><a href={'#/project/'+p.id+'/'+c.id} onClick={()=>{if(chapterId===c.id)document.getElementById('chapter-'+c.id)?.scrollIntoView({behavior:'instant'});}} key={c.id} aria-current={active===c.id?'location':undefined}><span>{String(i+1).padStart(2,'0')}</span>{c.title}</a>)}</nav><div className="toc-foot">设计过程 / 体验分析<br/>完整页面连续展示 · 点击放大</div></aside>
 <article className="case-content">{p.chapters.map((c,i)=><section className="case-chapter" id={'chapter-'+c.id} key={c.id}><div className="chapter-label"><span>{String(i+1).padStart(2,'0')}</span><span>{c.title}</span></div><h2>{c.lead}</h2><div className="chapter-body">{c.body.map((text,j)=><p key={j}>{text}</p>)}</div>{c.id==='evidence'?<ResearchPanel id={p.id}/>:c.id==='experience'?<ExperiencePanel id={p.id} mode={p.category==='interior'?'scenarios':'all'}/>:c.id==='validation'?<ReflectionPanel id={p.id}/>:c.id==='app-prototype'?<Su7Prototype onOpen={setLightbox}/>:<div className="source-boards">{c.pages.map(page=>{const src=displayPage(p.source,page);const size=dimensions[pageImage(p.source,page) as keyof typeof dimensions];return <figure key={page}><button className="source-board" onClick={()=>setLightbox(page)} aria-label={'放大完整页面第 '+page+' 页'}><img src={src} alt={pageTitles[p.source][page-1]} width={size?.width} height={size?.height} loading="lazy"/><span className="board-enlarge"><Maximize2 size={16}/> 放大完整页面</span></button><figcaption><span>{pageTitles[p.source][page-1]}</span><span>原稿 P.{String(page).padStart(2,'0')}</span></figcaption></figure>})}</div>}</section>)}<div className="case-source"><span className="eyebrow">SOURCE MATERIAL</span><p>{sources[p.source].name}</p><span>完整展示用户提供的最新文件；新增案头研究附公开来源，补充分析与项目反思单独呈现。</span></div></article></div>
 <div className="case-next wrap"><a href={'#work-'+p.category}><ArrowLeft size={19}/> 返回分类</a><a href={'#/project/'+next.id}><span>继续浏览</span><strong>{next.title}</strong><ArrowRight size={25}/></a><a className="case-top" onClick={()=>window.scrollTo({top:0,behavior:'instant'})} href={'#/project/'+p.id} aria-label="返回项目顶部"><ArrowUp size={20}/></a></div>
 <dialog ref={modal} className="board-dialog" aria-label="完整页面放大阅读" onCancel={()=>setLightbox(null)}><div className="board-toolbar"><span>{p.title} <small> / {typeof lightbox==='number'?'P.'+lightbox:'App 原型'}</small></span><div><button onClick={()=>setZoom(z=>Math.max(.75,z-.25))} aria-label="缩小原稿" disabled={zoom<=.75}><Minus size={20}/></button><span className="zoom-label">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(3,z+.25))} aria-label="放大原稿" disabled={zoom>=3}><Plus size={20}/></button><button onClick={()=>setLightbox(null)} aria-label="关闭原稿"><X size={22}/></button></div></div><div className="board-scroll">{lightbox!==null&&<img className={typeof lightbox==='string'?'app-screen-full':undefined} src={typeof lightbox==='number'?displayPage(p.source,lightbox):lightbox} alt={typeof lightbox==='number'?pageTitles[p.source][lightbox-1]:appScreens.find(screen=>screen.src===lightbox)?.title} style={{width: `${zoom*100}%`,maxWidth:typeof lightbox==='string'?`${850*zoom}px`:undefined}}/>}</div><div className="board-help">可放大并横向滚动查看细节 · Esc 关闭</div></dialog>
 </main>
}
